CREATE TABLE training_and_certification (
   TRAINING_ID INT(10) NOT NULL AUTO_INCREMENT,
   TRAINING_STATUS varchar(255) DEFAULT NULL,
   TRAINING_AND_CERTIFICATION_CATALOG_ID INT(10) NOT NULL AUTO_INCREMENT,
   EMPLOYEE_ID BIGINT(10) ZEROFILL,
   PRIMARY KEY (TRAINING_ID),
   FOREIGN KEY (EMPLOYEE_ID) REFERENCES employee(EMPLOYEE_ID),
   FOREIGN KEY (RAINING_AND_CERTIFICATION_CATALOG_I) REFERENCES training_and_certification_catalog(TRAINING_AND_CERTIFICATION_CATALOG_ID)
 )  ;
 CREATE TABLE training_and_certification_catalog (
  TRAINING_AND_CERTIFICATION_CATALOG_ID INT(10) NOT NULL AUTO_INCREMENT,
  TRAINING_TYPE varchar(255) DEFAULT NULL,
  TRAINING_FILTER_TYPE varchar(255) DEFAULT NULL,
  TRAINING_NAME varchar(255) DEFAULT NULL,
    DURATION varchar(255) DEFAULT NULL,
    TRAINING_LINK varchar(255) DEFAULT NULL,
  TRAINING_ID INT(10) NOT NULL,
 PRIMARY KEY (training_and_certification_catalog_id),
 FOREIGN KEY (TRAINING_ID) REFERENCES training_and_certification(TRAINING_ID)
);